### ISSUE TITLE
Frequent Kernel Panic in iOS when using Model Targets

### ISSUE THREAD

**Issue by internAshK** [PTCInc/vuforia-engine#110]
**Summarize the bug:**
Kernel Panic (forced restart) happens after few minutes of usage in the Experience created using Vuforia Model Targets in Unity 2022LTS on iPad 9th Gen

**Observed problem**
Kernel Panic and app close

**Reproducible steps**
1. Open an application with Model Target on iPad 9th Gen, run for few minutes, it does kernel panic

**Affected device:**
 - Name: iPad 9th Gen
 - OS: ios 17.4.1

**Workaround**
This is a random issue, and after sometimes it does not arise...After Kernel Panic -> closing the app and restarting fixed it for some time.

**Device or platform logs**
Attached Panic Logs -
[Uploading panic-full-2024-03-22-164406.000.txt…]()

**Comment by ptc-pscheper** [comment]
Hi there,

Please reproduce the issue by using our [Core Samples](https://assetstore.unity.com/packages/templates/packs/vuforia-core-samples-99026) and running the "Model Targets" scene to verify the issue is related to Model Targets specifically.

Also I have a few more questions:
- The log attached is a link to this issue, not the log itself. Can you attach the correct logs?
- When opening the application are you tracking the target or just letting Engine run?

**Comment by internAshK** [comment]
Okay will try this with Core Samples. We are tracking the target, it gets tracked and then there is animation. It usually goest to kernel panic state when either it is tracked and we are moving around the object, or when animations are playing

Also, here are the logs - 
[panic-full-2024-03-22-164406.000.txt](https://github.com/PTCInc/vuforia-engine/files/14771777/panic-full-2024-03-22-164406.000.txt)

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
