### ISSUE TITLE
Camera feed doesn't adapt to lighting conditions (Lenovo Tab P11 Pro (2nd Gen))

### ISSUE THREAD

**Issue by D3LV4R** [PTCInc/vuforia-engine#111]
**Summarize your device feedback**
When using any Vuforia related app at the Lenovo Tab P11 Pro (2nd Gen) the camera feed gets very dark in poor lighting conditions. I have already tried different devices and apps. In brighter lighting conditions everything works fine. The Lenovo Tab P11 Pro (1st Gen) doen't have this problem. 

**Describe your device**
The Lenovo Tab P11 Pro (2nd Gen) is a tablet. We use it to scan posters to show additional information and 3D modells. 

**Business Impact**
I'm working at a university of applied sciences. We show people results of today's science. 

**Link to device manufacturer / device specifications**
no problem: https://www.lenovo.com/de/de/p/tablets/android-tablets/lenovo-tab-series/lenovo-tb-j706/zzitztatb0j
problem: https://www.lenovo.com/de/de/departsales/c/Tab-P11-Pro-2nd-Gen/p/LEN103L0011

**Additional context**
Screenshot of the official Vuforia View Play Store App
![Screenshot](https://github.com/PTCInc/vuforia-engine/assets/18441978/9816bfe8-9305-493a-b7e4-3f26e8ed3535)

Same lighting condition when using the normal camera app
![Camera](https://github.com/PTCInc/vuforia-engine/assets/18441978/b89eae9b-ecc7-48e7-8656-5d069eccd355)

**Comment by ptc-pscheper** [comment]
Hi there, sadly we do not provide technical support for other Vuforia products such as Vuforia Studio and the Vuforia View app via this issue repository. I recommend to create a new support case through the [PTC eSupport portal](https://www.ptc.com/en/support/case-logger?&msg=1) or reach out via our [Vuforia Studio Community Forums](https://community.ptc.com/t5/Vuforia-Studio/bd-p/studio). 

 I will close this ticket as this is not related to the public Vuforia Engine SDK. Apologies I cannot be of more help.

**Comment by ptc-pscheper** [comment]
Hi there, in that case I apologize! I will keep this ticket open as a bug report and will check with the team. Do note that this device is not part of our recommended device list (only in the ARCore supported device list) so support can be limited.

**Comment by ptc-emaggio** [comment]
@D3LV4R this problem is likely unrelated to Vuforia Engine as it has been independently reported on the ARCore forum as well https://github.com/google-ar/arcore-android-sdk/issues/1627 . 

You could try to switch ARCore camera off by using the `VISION_ONLY` fusion provider but this would limit some Engine capabilities

see these two links:
https://developer.vuforia.com/sites/default/files/references/unity/group__VuforiaApplicationGroup.html#gafa43fb4756bd67edb0ea1bca50033dce

https://developer.vuforia.com/library/environments/vuforia-fusion

**Comment by ptc-pscheper** [comment]
Great find, thanks @ptc-emaggio. If you can turn off ARCore as stated above we can at least limit this issue to ARCore or Vuforia.

**Comment by ptc-emaggio** [comment]
Thanks @D3LV4R for the test. Could you please share the Android log? https://developer.android.com/studio/debug/logcat

**Comment by ptc-emaggio** [comment]
@D3LV4R thanks for the information. This indicates that the Android API we invoke internally to set exposure does not respond correctly. This can be either a camera driver issue (sometimes fixed by an OS update) or they just did not bother to implement it at all. Unfortunately it is unlikely there is anything  we can do on our side to solve this problem.
