### ISSUE TITLE
There is no Add Virtual Button in Image Target

### ISSUE THREAD

**Issue by semi67764** [PTCInc/vuforia-engine#116]
![image](https://github.com/PTCInc/vuforia-engine/assets/158143292/052ef462-00a9-447e-ac0d-9a330f3147ee)

where is it?

and why youtube tutorital just let us know click "Add Virtual Button", even there is nothing

**Comment by ptc-pscheper** [comment]
Virtual Button were deprecated since August 2023 (10.17) and were removed last month (v10.22). Here are some recommendations:
- Use a Canvas set to World Space, attach it as a child to the Image Target GameObject, add a UI button, and use ray-casting to let users trigger it by tapping on the screen.
- Create runtime image targets for the cropped sub-sections of the original Image Target and then check if the whole target is being tracked but any of the sub-targets are not.
- Run a hand-tracking solution like MRTK and use that to figure out if a finger occludes an area of the target.

Because this is a deprecated and removed feature I will close this ticket. If you wish the feature to be returned, you should create a feature request and share your use-cases for our product management team to consider the feature.

**Comment by semi67764** [comment]
Thanks you
 may i ask you 1 question more?
Is there any Youtube Link? like video tutorial about Virtual Button

2024년 4월 25일 (목) 오후 5:05, Patrick Scheper ***@***.***>님이 작성:

**Comment by ptc-pscheper** [comment]
Unfortunately there are no YouTube tutorials how to use one of the workaround as of today as far as I know.
