### ISSUE TITLE
Error Vuforia Engine

### ISSUE THREAD

**Issue by trixzu** [PTCInc/vuforia-engine#138]
In the Vuforia package, there's an error. Please see the attached photo. I'm trying my best to connect the Vuforia engine in Unity 3D, but I still have an error. I don't know what to do. :<

![Screenshot 2024-06-19 222619](https://github.com/PTCInc/vuforia-engine/assets/139488617/88d35a92-2b60-4854-842e-54fb1a8d27cd)

**Comment by ptc-thesbyro** [comment]
Hi @trixzu, 

Please re-create a bug ticket following the template provided for the type of issue. We need more details on how this error happened and reproducible steps to investigate it. Otherwise, we cannot help.

Your issue has been closed as it does not follow our contribution guidelines. To ensure effective and timely support, it is mandatory to follow the guidelines and use the templates we have provided when submitting a bug report or feature feedback. However, I encourage you to re-submit your report or feedback using the appropriate template. 

Please check out our [Contribution Guidelines](https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md) for issue requirements. 

Thank you,

**Comment by trixzu** [comment]
Hi @ptc-thesbyro,

Thank you for your response. The issue is that when I go to the XR plugin and install it, it shows the error depicted in the provided photo. I just want to know—after adding the Vuforia package and following the instructions found on the Vuforia portal, I'm not sure if the Vuforia Engine package can be fully utilized because of that error. I'm a college student and I don't have knowledge in Unity 3D and Vuforia, and I badly need this for making an app for my capstone project. Sorry for any inconvenience or confusion caused. Any guidance or assistance you can provide would be greatly appreciated.

Thank you,

**Comment by ptc-thesbyro** [comment]
To my knowledge, if you import the Vuforia Engine, it will include all dependencies in the installation. Is there a pop-up when you install the OpenXR Plugin after you already imported Vuforia Engine? Click "No" if it asks you to _enable native platform backends for the new input system_.
<img width="245" alt="warning-new-input-system-restart-no-vuforia-eyewear-sample" src="https://github.com/PTCInc/vuforia-engine/assets/67105337/54610f77-46f2-46fc-8a50-325f0e69fd9e">

**Comment by ptc-epassaro** [comment]
Hi @trixzu, as @ptc-thesbyro mentioned, please check out our [Contribution Guidelines](https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md) for issue requirements and open a new issue following our `Bug Report` template.

If possible, please include the following info so that we can try to help you to the best of our capacity:
- name of the XR package you tried to import
- if you have the `XR Core Utilities` package included in your project
- if you imported the Vuforia Engine asset from the AssetStore or the Vuforia Engine package from our [Developer Portal](https://developer.vuforia.com/downloads/sdk)
