### ISSUE TITLE
Does Vuforia Engine support the latest RealWear devices?

### ISSUE THREAD

**Issue by tsoen** [PTCInc/vuforia-engine#139]
**Describe your device**
Hello,
I noticed the Recommended Devices documentation page (https://developer.vuforia.com/library/platform-support/recommended-devices) only mentions HMT-1 and HMT-1Z1 RealWear devices.
However, it looks like the Vuforia View app support RealWear HMT-1 and HMT-1Z1, Navigator 500 and Navigator 520 as stated here : https://support.ptc.com/help/vuforia/studio/en/index.html#page/Studio_Help_Center%2Fcommon%2FViewSupportedReq.html%23

Does Vuforia Engine support the latest version of RealWear devices ?

Best regards

**Comment by ptc-thesbyro** [comment]
Hi,

The Recommended Devices documentation page lists devices that we, to various extents, actively test with the Vuforia Engine on. These devices are certain to work for all features unless otherwise noted. Devices not listed on the page are still likely to work if they have the capabilities required for Vuforia Engine and its features. 

The Vuforia View app only uses a subset of the Engine SDK features, and its functionality is end-to-end tested on the specified supported devices. 

Kind regards,

**Comment by ptc-thesbyro** [comment]
Updated title for further reference and closing ticket.
