### ISSUE TITLE
Model target recognized but not augmented

### ISSUE THREAD

**Issue by riccardokhm** [PTCInc/vuforia-engine#14]
**Summarize the bug:**
Hi, I'm encountering a tracking issue where the engine successfully recognizes the object but no model is augmented. I have tried different viewpoints and lightning condition but nothing.
Please find attached some videos.

https://user-images.githubusercontent.com/63868396/229166686-d1e7cc67-a75f-4e43-98f9-c1f0e58c40d1.MOV

**Comment by ptc-pscheper** [comment]
Hi there, could you please share additional information? Without additional information support cannot be provided and the issue is closed. Relevant information is usually within the bug report template and documented here: https://github.com/PTCInc/vuforia-engine/blob/master/CONTRIBUTING.md#how-to-write-a-bug-report

**Comment by ptc-pscheper** [comment]
This issue is closed due to inactivity. Feel free to re-open or create a new bug report in the future.
