### ISSUE TITLE
Video is not on image target when scanning

### ISSUE THREAD

**Issue by AmiraJomaa** [PTCInc/vuforia-engine#155]
https://github.com/user-attachments/assets/05ea979e-8f0f-423c-9887-d9a01933c946

I am using Unity version 2022.3.21f1 With the Vuforia package Version'10', I am integrating a video on a real image within the scope of Augmented Reality. For this, I create a plane on the image target(which is a cloud reco) in Hierarchy and assign a video to the inspector window. However, when I test, the video does not show on the real image target : it starts on the image target which is the video player assigned to not to the real image target ,it's really confused thing and image target(which is in Hierarchy ) when testing it moves around not fixed at one position : the position & rotation values are changes at the meantime.

As it is shown in the video the image get scanned the video start playing but not shown on the image

**Comment by ptc-emaggio** [comment]
Thanks @AmiraJomaa for the report, can you reproduce the problem with the [Vuforia Core Sample](https://assetstore.unity.com/packages/templates/packs/vuforia-core-samples-99026) which also shows how to attach a Video to an image target?

**Comment by AmiraJomaa** [comment]
the configuration used in the Vuforia Core Sample is the same i used & it's a cloud recognition image target + the video is getted from server. But the problem didn't fixed

**Comment by ptc-emaggio** [comment]
Thanks @AmiraJomaa could you please clarify if the problem can be reproduced on the Core Sample?

**Comment by ptc-epassaro** [comment]
Hi @AmiraJomaa, as @ptc-emaggio pointed out, if the video on the Fissure ImageTarget in the Core Samples works for you, then it's highly likely that the problem is specific to your project and not Vuforia.

In addition to the troubleshooting guide linked above, there are some things that I would recommend you to try:
1. Check the rotation of the GameObject with the VideoPlayer. For example, in the Core Samples, the plane of the Video Player is facing up, so the rotation on the x axis is 0, while from the images you linked on SO I can see that yours is set to 90. Unless the material you are using on the VideoPlayer is double sided, you will not see anything if the quad is facing away from the camera.
![Screenshot 2024-09-18 at 14 00 03](https://github.com/user-attachments/assets/3764ee1e-e71a-4c13-9fde-560fc6990a7a)
2. Start from an empty project, import Vuforia and add your CloudReco target with the VideoPlayer. See if the issue appears there too.
3. Make sure that the physical size of the ImageTarget in your scene matches the size of the real target you are using.
![Screenshot 2024-09-18 at 14 03 40](https://github.com/user-attachments/assets/1b0637ab-8d0d-4024-9d6e-7b5fb562d81c)

If the problem persists, you can send us the complete version number of Vuforia you are using and a list of the exact steps you are doing to set up the scene and we will try to reproduce the issue on our side.

Thank you, hope it helps!

**Comment by AmiraJomaa** [comment]
okay i created a new project as you said.
i create as it is shown in the capture a cloud recognition gameobject + image target + ar camera still having the same issue
![Capture d'écran 2024-09-20 153131](https://github.com/user-attachments/assets/26a73aa8-6029-4bb2-ae7a-1a0b2ca1c800)

**Comment by AmiraJomaa** [comment]
This is a video to see what's happening:
https://github.com/user-attachments/assets/95e7da71-ce34-4d89-97cb-f2756a29a5e7

the video mesh renderer also start as disabled not enabled btw.
i am using Unity 2022.3.21f1 + Vuforia 10.25.4 ( even with Vuforia 10.22.5 had same thing).

**Comment by AmiraJomaa** [comment]
I Tried something : the image target if it a normal image target the video works fine , the problem is on the cloud recognition targets.
i change this :
![Capture d'écran 2024-09-20 165712](https://github.com/user-attachments/assets/421343d5-cc75-4b57-8dcb-2ca109c33474)
to this : 
![Capture d'écran 2024-09-20 165659](https://github.com/user-attachments/assets/2410a4b2-44b7-406f-b6d7-9d258fc82cd9)
the video works normally.
but i need the cloud recognition in my app

**Comment by ptc-epassaro** [comment]
Hi @AmiraJomaa, I would recommend you to check out our [Working with Cloud Recognition in Unity](https://developer.vuforia.com/library/cloud-recognition/working-cloud-recognition) documentation page. From the video you attached, it looks like some components might be missing in your scene.

You can try to import Vuforia and then this package into an empty project:
[cloudreco_min_setup.unitypackage.zip](https://github.com/user-attachments/files/17100902/cloudreco_min_setup.unitypackage.zip)
This uses the `SimpleCloudRecoEventHandler` script mentioned in the documentation. The script is attached to the CloudRecognition GameObject and references the ImageTarget.

Hope this helps!

**Comment by AmiraJomaa** [comment]
Hi @ptc-epassaro, Thanks for your answering. Well i tried importing Vuforia and then the package you gave me into an empty project and i tested the scene.
I got the same result i have it : the video is moving around.

**Comment by ptc-thesbyro** [comment]
Hi @AmiraJomaa, you closed this issue as completed. Did you find the solution to your problem? Would you be able to share it here, in case others experience the same issue?

Thank you,
