### ISSUE TITLE
Target Manager rounds image target's width size to one decimal point

### ISSUE THREAD

**Issue by daniel1v** [PTCInc/vuforia-engine#161]
**Summarize the bug:**
After uploading an image to the Target Manager and typing in a size with more than 1 decimal places, the size is rounded to 1 decimal place.

**Observed problem**
I've tried to upload several different images and experiencing following issue:

When I type in a size like 0.55, the image target is generated and everything looks fine. After downloading the database and opening the xml file, the target size is set to 0.6. Whe I type in 0.54999, the size is rounded to 0.5.

**Expected result**
The size in the xml should be the same as in the target manager.

**Comment by ptc-thesbyro** [comment]
Hi @daniel1v,

Thanks for reaching out. 

Let me do a bit of investigating and get back to you.

**Comment by ptc-thesbyro** [comment]
Hi @daniel1v, 

We have verified that there is a bug on the Target Manager UI and are working on a fix. I will let you know as soon as we have it ready. 

In the meantime, you can wait until the fix is released or manually edit the downloaded XML dataset sizes to the correct dimensions.  

We apologize for the inconvenience.

**Comment by ptc-thesbyro** [comment]
Hi @daniel1v,

The issue where the Target Manager was rounding up values should now be fixed. Do let us know if you still see discrepancy between the input value and the XML dataset output.

**Comment by daniel1v** [comment]
Hi @ptc-thesbyro,

after a quick test, I can confirm, that the issue is resolved. Thank you for the support.
