### ISSUE TITLE
Missing API in C# language docs

### ISSUE THREAD

**Issue by RyuuyaS** [PTCInc/vuforia-engine#64]
**Summarize the bug:**
Right now, the latest version of Vuforia comes with code examples in C, but when I try to convert it to the C# to use in Unity, I found some missing APIs on the API page, like VuAnchorOberserConfig, IVUDevicePoseObserver, ...

**Expected result**
Show all the APIs can use.

**Additional comments**
Please feel free to add any other details about the problem here.
This is my thought but can you add a C# example code to the API overview like C, this will provide a better experience and more clear

**Comment by ptc-ddowning** [comment]
Hello @RyuuyaS,

You are correct that Vuforia Engine C APIs differ from the C# APIs. This is by design.

Vuforia Engine provides several resources that can be used to help with understand developing with C# APIs:
1. [Unity Sample Apps](https://developer.vuforia.com/downloads/samples) that demonstrate Engine's core features, functionality and best practices
2. An extensive, searchable [library](https://library.vuforia.com/) that both references the provided samples, and with instructive code blocks
3. A searchable, [C# API reference](https://library.vuforia.com/sites/default/files/references/unity/index.html) library

Hopefully, this will help you to better understand and use Vuforia Engine C# APIs.

Thanks,
Vuforia Engine Support
